name: aquariatric
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b09'
    - '#fefffa'
    - '#5a6868'
    - '#af816a'
    - '#e5d2a8'
  brandStrength: 0.6875
  lightness: 0.5626965926494449
  saturation: 0.07752826111391187
  rhythmicContrast: 0.5820662877522409
purpose: []
