name: aquariatric
favicon: null
layout_spectrum: 0.24664
typography_spectrum: 0.48306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141319'
    - '#6185d1'
    - '#405992'
    - '#353446'
    - '#9fadc7'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
