name: aquariatric
favicon: null
layout_spectrum: 0.4732
typography_spectrum: 0.48306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#fffef9'
    - '#646076'
    - '#a4a2a5'
    - '#eecac2'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
