name: aquariatric
favicon: null
layout_spectrum: 0.44684
typography_spectrum: 0.79059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#3a3b3a'
    - '#c7c7c7'
    - '#848584'
    - '#ababab'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
